### ISSUE TITLE
Make MaxFileSize an input parameter

### ISSUE THREAD

**Issue by Blackbaud-BrianBlanchard** [blackbaud/skyux-avatar#16]
### Expected behavior

Make MaxFileSize an input parameter for SkyAvatar and account for larger sizes in the popup message when size is exceeded.

We can allow larger sizes because our upload process creates a smaller thumbnail image that is eventually used for the avatar.

### Actual behavior

MaxFileSize is a hard limit and consumers forced to set the public available property, but having the first class input is cleaner/safer.  Also, the error message is harder to read (e.g., max file size of 10000 KB).

### Severity

Low

### Impact

Low

**Comment by blackbaud-conorwright** [comment]
I would also really like this to be an input. Might just make a PR for it
