### ISSUE TITLE
Allow validation message to be customized: "Please choose an image that is less than 5 MB"

### ISSUE THREAD

**Issue by reyou** [blackbaud/skyux-avatar#48]
### Expected behavior
Having error message like Please choose an image that is less than 5 MB.

### Actual behavior
![image](https://user-images.githubusercontent.com/6571483/99088326-87935f00-2591-11eb-89c7-baa4786eb87c.png)

### Steps to reproduce
Use avatar control with file size 6MB while limitation is less.

### Severity
Medium

### Impact
Medium

[AB#1627024](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1627024)

**Comment by Blackbaud-TrevorBurch** [comment]
We updated this message in `4.1.2` to dynamically use the appropriate file size units.
